name: openhunt

services:
  openhunt-server:
    build: .
    ports:
      - '3002:3002'
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3002
      - DATABASE_URL=./data/openhunt.db
